services:
  app:
    build:
      dockerfile: Dockerfile
    environment:
      - DOMAIN=0.0.0.0:6475
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017
      - REDIS_ADDRESS=redis:6379
      - LOCAL_STORE_ROOT=uploads
      - LOCAL_STORE_URI_PREFIX=C:\Repositories\obert\mktextr\upload
    ports:
      - "6475:6475"
    networks:
      - app-network
    profiles:
      - all
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    profiles:
      - dev-only
      - all

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    profiles:
      - dev-only
      - all

networks:
  app-network:
    driver: bridge
