openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for mktextr
paths:
    /tasks/{taskId}/complete:
        get:
            tags:
                - mktextr
            summary: completeTask mktextr
            operationId: mktextr#completeTask
            parameters:
                - name: taskId
                  in: path
                  description: Unique identifier
                  required: true
                  schema:
                    type: string
                    description: Unique identifier
                    example: Atque ut nesciunt quos est.
                  example: Ut voluptatibus est dolorem.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TaskCompletionPayload2'
                        example:
                            texture:
                                - 78
                                - 111
                                - 110
                                - 32
                                - 111
                                - 112
                                - 116
                                - 105
                                - 111
                                - 32
                                - 109
                                - 111
                                - 108
                                - 101
                                - 115
                                - 116
                                - 105
                                - 97
                                - 101
                                - 46
            responses:
                "204":
                    description: No Content response.
    /textures:
        get:
            tags:
                - mktextr
            summary: getTextureByCoordinates mktextr
            operationId: mktextr#getTextureByCoordinates
            parameters:
                - name: worldId
                  in: query
                  description: WorldId
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: WorldId
                    example: Velit et repudiandae.
                  example: Autem velit placeat et.
                - name: x
                  in: query
                  description: Texture X
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: integer
                    description: Texture X
                    example: 5973966940440777230
                    format: int64
                  example: 6346180173533273027
                - name: "y"
                  in: query
                  description: Texture Y
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: integer
                    description: Texture Y
                    example: 3488679172165449929
                    format: int64
                  example: 5956353106596919979
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TextureReferencePayload'
                            example:
                                id: Molestiae ab id quo.
    /textures/{id}:
        get:
            tags:
                - mktextr
            summary: getTextureById mktextr
            operationId: mktextr#getTextureById
            parameters:
                - name: id
                  in: path
                  description: Texture ID
                  required: true
                  schema:
                    type: string
                    description: Texture ID
                    example: Saepe iure repellendus perferendis quasi et.
                  example: Cupiditate ut et quasi sit doloremque ut.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TextureReferencePayload'
                            example:
                                id: Recusandae sit a id nemo suscipit qui.
components:
    schemas:
        TaskCompletionPayload:
            type: object
            properties:
                taskId:
                    type: string
                    description: Unique identifier
                    example: Temporibus voluptate vel voluptas velit.
                texture:
                    type: string
                    description: The texture
                    example:
                        - 80
                        - 111
                        - 115
                        - 115
                        - 105
                        - 109
                        - 117
                        - 115
                        - 32
                        - 112
                        - 111
                        - 115
                        - 115
                        - 105
                        - 109
                        - 117
                        - 115
                        - 32
                        - 97
                        - 117
                        - 116
                        - 46
                    format: binary
            description: The texture payload
            example:
                taskId: Impedit recusandae reprehenderit et repellat qui.
                texture:
                    - 68
                    - 105
                    - 99
                    - 116
                    - 97
                    - 32
                    - 109
                    - 97
                    - 120
                    - 105
                    - 109
                    - 101
                    - 46
            required:
                - taskId
                - texture
        TaskCompletionPayload2:
            type: object
            properties:
                texture:
                    type: string
                    description: The texture
                    example:
                        - 70
                        - 117
                        - 103
                        - 105
                        - 116
                        - 32
                        - 110
                        - 101
                        - 109
                        - 111
                        - 32
                        - 100
                        - 111
                        - 108
                        - 111
                        - 114
                        - 101
                        - 109
                        - 46
                    format: binary
            description: Complete task
            example:
                texture:
                    - 67
                    - 111
                    - 110
                    - 115
                    - 101
                    - 113
                    - 117
                    - 97
                    - 116
                    - 117
                    - 114
                    - 32
                    - 105
                    - 109
                    - 112
                    - 101
                    - 100
                    - 105
                    - 116
                    - 32
                    - 118
                    - 111
                    - 108
                    - 117
                    - 112
                    - 116
                    - 97
                    - 115
                    - 32
                    - 97
                    - 100
                    - 105
                    - 112
                    - 105
                    - 115
                    - 99
                    - 105
                    - 32
                    - 99
                    - 111
                    - 110
                    - 115
                    - 101
                    - 99
                    - 116
                    - 101
                    - 116
                    - 117
                    - 114
                    - 32
                    - 118
                    - 111
                    - 108
                    - 117
                    - 112
                    - 116
                    - 97
                    - 116
                    - 101
                    - 32
                    - 113
                    - 117
                    - 105
                    - 97
                    - 46
            required:
                - texture
        TextureReferencePayload:
            type: object
            properties:
                id:
                    type: string
                    description: Unique identifier
                    example: Qui et.
            description: The texture unique reference
            example:
                id: Praesentium laborum corporis et.
tags:
    - name: mktextr
      description: Texture store
