swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /tasks/{taskId}/complete:
        patch:
            tags:
                - mktextr
            summary: completeTask mktextr
            operationId: mktextr#completeTask
            consumes:
                - multipart/form-data
            parameters:
                - name: taskId
                  in: path
                  description: ID of the task
                  required: true
                  type: string
                - name: CompleteTaskRequestBody
                  in: formData
                  required: true
                  schema:
                    $ref: '#/definitions/MktextrCompleteTaskRequestBody'
                    required:
                        - file
                        - filename
            responses:
                "200":
                    description: OK response.
            schemes:
                - http
    /textures:
        get:
            tags:
                - mktextr
            summary: getTextureByCoordinates mktextr
            operationId: mktextr#getTextureByCoordinates
            parameters:
                - name: worldId
                  in: query
                  description: WorldId
                  required: true
                  type: string
                - name: x
                  in: query
                  description: Texture X
                  required: true
                  type: integer
                - name: "y"
                  in: query
                  description: Texture Y
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/MktextrGetTextureByCoordinatesOKResponseBody'
                "202":
                    description: Accepted response.
                    schema:
                        $ref: '#/definitions/MktextrGetTextureByCoordinatesAcceptedResponseBody'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/MktextrGetTextureByCoordinatesBadRequestResponseBody'
            schemes:
                - http
    /textures/{id}:
        get:
            tags:
                - mktextr
            summary: getTextureById mktextr
            operationId: mktextr#getTextureById
            parameters:
                - name: id
                  in: path
                  description: Texture ID
                  required: true
                  type: string
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
definitions:
    MktextrCompleteTaskRequestBody:
        title: MktextrCompleteTaskRequestBody
        type: object
        properties:
            file:
                type: string
                description: The file to upload
                example:
                    - 70
                    - 97
                    - 99
                    - 101
                    - 114
                    - 101
                    - 32
                    - 100
                    - 105
                    - 99
                    - 116
                    - 97
                    - 32
                    - 99
                    - 111
                    - 110
                    - 115
                    - 101
                    - 113
                    - 117
                    - 97
                    - 116
                    - 117
                    - 114
                    - 32
                    - 100
                    - 111
                    - 108
                    - 111
                    - 114
                    - 101
                    - 115
                    - 32
                    - 114
                    - 101
                    - 114
                    - 117
                    - 109
                    - 46
                format: byte
            filename:
                type: string
                description: Name of the file
                example: Optio molestiae doloremque voluptate quia sequi ea.
        example:
            file:
                - 65
                - 32
                - 97
                - 117
                - 116
                - 32
                - 97
                - 115
                - 115
                - 117
                - 109
                - 101
                - 110
                - 100
                - 97
                - 32
                - 105
                - 112
                - 115
                - 117
                - 109
                - 32
                - 99
                - 117
                - 108
                - 112
                - 97
                - 32
                - 109
                - 97
                - 105
                - 111
                - 114
                - 101
                - 115
                - 46
            filename: Aliquid omnis nisi beatae.
        required:
            - file
            - filename
    MktextrGetTextureByCoordinatesAcceptedResponseBody:
        title: 'Mediatype identifier: application/get-result; view=default'
        type: object
        properties:
            baseMapUrl:
                type: string
                example: Cupiditate ut et quasi sit doloremque ut.
            contourMapUrl:
                type: string
                example: Velit et repudiandae.
            taskId:
                type: string
                example: Saepe iure repellendus perferendis quasi et.
        description: GetTextureByCoordinatesAcceptedResponseBody result type (default view)
        example:
            baseMapUrl: Dolorem quia consequatur saepe atque ut nesciunt.
            contourMapUrl: Est ad ut voluptatibus est dolorem quae.
            taskId: Autem velit placeat et.
    MktextrGetTextureByCoordinatesBadRequestResponseBody:
        title: 'Mediatype identifier: application/get-result; view=default'
        type: object
        properties:
            baseMapUrl:
                type: string
                example: Vel corporis numquam nesciunt quia sunt.
            contourMapUrl:
                type: string
                example: Iusto est ratione eum ut.
            taskId:
                type: string
                example: Sapiente omnis ipsam.
        description: GetTextureByCoordinatesBad RequestResponseBody result type (default view)
        example:
            baseMapUrl: Et tempore quia accusamus aut eaque atque.
            contourMapUrl: Sed est commodi dolor ut.
            taskId: Iste quis.
    MktextrGetTextureByCoordinatesOKResponseBody:
        title: 'Mediatype identifier: application/get-result; view=default'
        type: object
        properties:
            baseMapUrl:
                type: string
                example: Possimus possimus aut.
            contourMapUrl:
                type: string
                example: Impedit recusandae reprehenderit et repellat qui.
            taskId:
                type: string
                example: Temporibus voluptate vel voluptas velit.
        description: GetTextureByCoordinatesOKResponseBody result type (default view)
        example:
            baseMapUrl: Fugit nemo dolorem.
            contourMapUrl: Consequatur impedit voluptas adipisci consectetur voluptate quia.
            taskId: Dicta maxime.
