swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /tasks:
        get:
            tags:
                - mktextr
            summary: GetTaskQueue mktextr
            operationId: mktextr#GetTaskQueue
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/MktextrGetTaskQueueResponseBody'
            schemes:
                - http
    /tasks/{taskId}/complete:
        patch:
            tags:
                - mktextr
            summary: completeTask mktextr
            operationId: mktextr#completeTask
            consumes:
                - multipart/form-data
            parameters:
                - name: taskId
                  in: path
                  description: ID of the task
                  required: true
                  type: string
                - name: CompleteTaskRequestBody
                  in: formData
                  required: true
                  schema:
                    $ref: '#/definitions/MktextrCompleteTaskRequestBody'
                    required:
                        - file
                        - extension
            responses:
                "200":
                    description: OK response.
            schemes:
                - http
    /textures:
        get:
            tags:
                - mktextr
            summary: getTextureByCoordinates mktextr
            operationId: mktextr#getTextureByCoordinates
            parameters:
                - name: worldId
                  in: query
                  description: WorldId
                  required: true
                  type: string
                - name: x
                  in: query
                  description: Texture X
                  required: true
                  type: integer
                - name: "y"
                  in: query
                  description: Texture Y
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/GetTextureByCoordinatesResponse'
                "206":
                    description: Partial Content response.
                    schema:
                        $ref: '#/definitions/GetTextureByCoordinatesResponse'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/GetTextureByCoordinatesResponse'
            schemes:
                - http
definitions:
    GetTextureByCoordinatesResponse:
        title: GetTextureByCoordinatesResponse
        type: object
        properties:
            baseMapUrl:
                type: string
                example: Facere dicta consequatur dolores rerum.
            contourMapUrl:
                type: string
                example: Optio molestiae doloremque voluptate quia sequi ea.
            sub_state:
                type: string
                example: A aut assumenda ipsum culpa maiores.
            texture_set_state:
                type: string
                example: Sed est commodi dolor ut.
        example:
            baseMapUrl: Sed dolor dolores.
            contourMapUrl: Qui aliquid sapiente.
            sub_state: Enim nihil.
            texture_set_state: Aliquid omnis nisi beatae.
    MktextrCompleteTaskRequestBody:
        title: MktextrCompleteTaskRequestBody
        type: object
        properties:
            extension:
                type: string
                description: ID of the task
                example: Laborum excepturi in.
            file:
                type: string
                description: The file to upload
                example:
                    - 86
                    - 101
                    - 110
                    - 105
                    - 97
                    - 109
                    - 32
                    - 101
                    - 114
                    - 114
                    - 111
                    - 114
                    - 32
                    - 108
                    - 97
                    - 117
                    - 100
                    - 97
                    - 110
                    - 116
                    - 105
                    - 117
                    - 109
                    - 32
                    - 98
                    - 108
                    - 97
                    - 110
                    - 100
                    - 105
                    - 116
                    - 105
                    - 105
                    - 115
                    - 32
                    - 118
                    - 105
                    - 116
                    - 97
                    - 101
                    - 46
                format: byte
        example:
            extension: Exercitationem dolor debitis nisi voluptatem aut perferendis.
            file:
                - 65
                - 98
                - 32
                - 112
                - 111
                - 115
                - 115
                - 105
                - 109
                - 117
                - 115
                - 32
                - 113
                - 117
                - 105
                - 97
                - 32
                - 109
                - 111
                - 108
                - 101
                - 115
                - 116
                - 105
                - 97
                - 115
                - 32
                - 97
                - 100
                - 105
                - 112
                - 105
                - 115
                - 99
                - 105
                - 32
                - 111
                - 109
                - 110
                - 105
                - 115
                - 46
        required:
            - file
            - extension
    MktextrGetTaskQueueResponseBody:
        title: MktextrGetTaskQueueResponseBody
        type: object
        properties:
            tasks:
                type: array
                items:
                    type: string
                    example: Est ad ut voluptatibus est dolorem quae.
                example:
                    - Omnis ipsam voluptatibus vel.
                    - Numquam nesciunt.
                    - Sunt nam iusto est ratione eum ut.
        example:
            tasks:
                - Quis quis.
                - Tempore quia accusamus aut eaque atque.
