openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for mktextr
paths:
    /tasks/{taskId}/complete:
        get:
            tags:
                - mktextr
            summary: completeTask mktextr
            operationId: mktextr#completeTask
            parameters:
                - name: taskId
                  in: path
                  description: Unique identifier
                  required: true
                  schema:
                    type: string
                    description: Unique identifier
                    example: Fugit nemo dolorem.
                  example: Consequatur impedit voluptas adipisci consectetur voluptate quia.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TaskCompletionPayload2'
                        example:
                            texture:
                                - 68
                                - 105
                                - 99
                                - 116
                                - 97
                                - 32
                                - 113
                                - 117
                                - 97
                                - 101
                                - 32
                                - 118
                                - 101
                                - 108
                                - 105
                                - 116
                                - 32
                                - 118
                                - 111
                                - 108
                                - 117
                                - 112
                                - 116
                                - 97
                                - 116
                                - 101
                                - 115
                                - 32
                                - 100
                                - 111
                                - 108
                                - 111
                                - 114
                                - 46
            responses:
                "204":
                    description: No Content response.
    /textures/{id}:
        get:
            tags:
                - mktextr
            summary: getTextureById mktextr
            operationId: mktextr#getTextureById
            parameters:
                - name: id
                  in: path
                  description: Texture ID
                  required: true
                  schema:
                    type: string
                    description: Texture ID
                    example: Impedit recusandae reprehenderit et repellat qui.
                  example: Dicta maxime.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TextureReferencePayload'
                            example:
                                id: Enim non recusandae sit a.
components:
    schemas:
        TaskCompletionPayload:
            type: object
            properties:
                taskId:
                    type: string
                    description: Unique identifier
                    example: Corporis nihil autem.
                texture:
                    type: string
                    description: The texture
                    example:
                        - 86
                        - 101
                        - 114
                        - 111
                        - 32
                        - 100
                        - 101
                        - 115
                        - 101
                        - 114
                        - 117
                        - 110
                        - 116
                        - 32
                        - 114
                        - 101
                        - 109
                        - 32
                        - 105
                        - 100
                        - 32
                        - 109
                        - 111
                        - 108
                        - 101
                        - 115
                        - 116
                        - 105
                        - 97
                        - 101
                        - 32
                        - 113
                        - 117
                        - 105
                        - 100
                        - 101
                        - 109
                        - 32
                        - 110
                        - 105
                        - 104
                        - 105
                        - 108
                        - 46
                    format: binary
            description: The texture payload
            example:
                taskId: Qui et.
                texture:
                    - 80
                    - 114
                    - 97
                    - 101
                    - 115
                    - 101
                    - 110
                    - 116
                    - 105
                    - 117
                    - 109
                    - 32
                    - 108
                    - 97
                    - 98
                    - 111
                    - 114
                    - 117
                    - 109
                    - 32
                    - 99
                    - 111
                    - 114
                    - 112
                    - 111
                    - 114
                    - 105
                    - 115
                    - 32
                    - 101
                    - 116
                    - 46
            required:
                - taskId
                - texture
        TaskCompletionPayload2:
            type: object
            properties:
                texture:
                    type: string
                    description: The texture
                    example:
                        - 84
                        - 101
                        - 109
                        - 112
                        - 111
                        - 114
                        - 105
                        - 98
                        - 117
                        - 115
                        - 32
                        - 118
                        - 111
                        - 108
                        - 117
                        - 112
                        - 116
                        - 97
                        - 116
                        - 101
                        - 32
                        - 118
                        - 101
                        - 108
                        - 32
                        - 118
                        - 111
                        - 108
                        - 117
                        - 112
                        - 116
                        - 97
                        - 115
                        - 32
                        - 118
                        - 101
                        - 108
                        - 105
                        - 116
                        - 46
                    format: binary
            description: Complete task
            example:
                texture:
                    - 80
                    - 111
                    - 115
                    - 115
                    - 105
                    - 109
                    - 117
                    - 115
                    - 32
                    - 112
                    - 111
                    - 115
                    - 115
                    - 105
                    - 109
                    - 117
                    - 115
                    - 32
                    - 97
                    - 117
                    - 116
                    - 46
            required:
                - texture
        TextureReferencePayload:
            type: object
            properties:
                id:
                    type: string
                    description: Unique identifier
                    example: Facere quibusdam.
            description: The texture unique reference
            example:
                id: Dolore voluptatem incidunt.
tags:
    - name: mktextr
      description: Texture store
